### ISSUE TITLE
do you have a config to disable stuff and enable stuff?

### ISSUE THREAD

**Issue by DarthMDev** [mikebryant/codeclimate-pylint#1]

**Comment by DarthMDev** [comment]
just  a double check :)

**Comment by mikebryant** [comment]
It will honour pylintrc files in the repo, as per http://docs.pylint.org/run.html#command-line-options

**Comment by DarthMDev** [comment]
so yes or no can you enable stuff and disable stuff like in pep8

**Comment by mikebryant** [comment]
Yes, you can

Option 1, `.codeclimate.yml`:

```
---
engines:
  pylint:
    enabled: true
    checks:
      abstract-method:
        enabled: false
```

Option 2, `pylintrc`
Create a file in your repo at the top level called `pylintrc`

``````
[MESSAGES CONTROL]
#enable=
disable=E1608,abstract-method,etc
``` - for the full syntax of this file run `pylint --generate-rcfile`
``````
